---
title: "sgtests"
output: html_notebook
---

```{r}
data <- read.csv('data/fakeresponses.csv',stringsAsFactors = F)
head(data)
```
```{r}
as.data.frame(data %>% group_by(What.are.you.most.interested.in.) %>% 
  summarise(n = n()) %>% 
  filter(n==max(n)))[[2]]

d <- "Timestamp"
as.factor(data[,d])
  
```



```{r}
data$assignment <- rep(0,nrow(data))
by.interest <- split(data,as.factor(data$What.are.you.most.interested.in.))
by.interest
```
```{r}
# we will be ok with groups of size num_groups (+/- 1)
group_size <- 4

# for each data frame, take groups of 4 until you have too few (in the case of num_groups = 4, this would mean < 3).
# for this data, there would be (2,1,1,0,1,2) left over in each interest group

cur_group <- 1
for(i in seq_along(by.interest)){
  cur.df <- by.interest[[i]]
  num_groups <- floor(nrow(cur.df)/group_size)
  assignments <- c()
  if(nrow(cur.df)>=group_size){
    for(g in cur_group:(cur_group+(num_groups-1))){
        assignments <- c(assignments,rep(cur_group,group_size))
        # only shuffle if num_groups > 1
        cur_group <- cur_group+1
    }
    rem <- nrow(cur.df) %% group_size
    assignments <- c(assignments,rep(0,rem))
    by.interest[[i]]$assignment <- assignments
  }
}
```

```{r}
# then join the data back, add column 'remainders', set = T for the leftovers (assignment==0)
# separate into 'assigned' and 'unassigned' dfs

data2 <- bind_rows(by.interest)
assigned <- data2[data2$assignment != 0,]
unassigned <- data2[data2$assignment == 0,]

# take the 'assigned' df, split by interest again.
# shuffle to make diverse-skilled groups, re-assign
# join the dfs back.

a.by.interest <- split(assigned,as.factor(assigned$What.are.you.most.interested.in.))
a.by.interest

# now you have a bunch of assigned groups, and at most (num_groups-2)*(num_interest_groups) unassigned people [in this case, a max of 12]
# how do we assign those people? 
```

```{r}
  # calculates group memberships, returns table
  # function takes in 's', a list of dfs
  make_groups <- function(s, group_size){
    
    group_size <- as.numeric(group_size)
    cur_group <- 1
    
    for(group in seq_along(s)){
      s[[group]]$assignment <- 0
      cur.df <- s[[group]]
      num_groups <- floor(nrow(cur.df)/group_size)
      assignments <- c()

      if(nrow(cur.df)>=group_size){
        
        for(g in cur_group:(cur_group+(num_groups-1))){
          assignments <- c(assignments,rep(cur_group,group_size))

          cur_group <- cur_group+1
        }
        rem <- nrow(cur.df) %% group_size
        assignments <- c(assignments,rep(0,rem))
        # only shuffle if num_groups > 1
        if(num_groups > 1){
            s[[group]]$assignment <- assignments
          }
        else{
            s[[group]]$assignment <- assignments
          }
      }
    }
    
    final.df <- s
    for(i in seq_along(final.df)){
      r <- c(final.df[[i]] %>% rownames() %>% as.numeric())
      final.df[[i]]$topics <- t()[r,]$lda
      final.df[[i]]$interest <- t()[r,]$interest
      final.df[[i]]$program <- t()[r,]$program
      final.df[[i]]$graded <- t()[r,]$graded
    }
    final.df <- bind_rows(final.df)
    final.df
  }
```

```{r}
for(i in 8:ncol(data)){
  print(gsub("\\.","",regmatches(names(data)[i],regexpr("\\w+",names(data[i])),invert=T)[[1]][2]))
}
# names(data)
```
```{r}
allskills <- list()
data$skills <- ""
for(i in 1:nrow(data)){
  tempskills <- ""
  for(j in 8:15){
    if(data[i,names(data)[j]] == "strengths"){
      tempskills <- paste(tempskills,names(data)[j])
    }
  }
  data$skills[i] <- tempskills
}
```


```{r}
substr(";poop",2,nchar(";poop"))
```
```{r}
# Library
library(fmsb)

# Create data: note in High school for Jonathan:
data1=as.data.frame(matrix( sample( 2:20 , 10 , replace=T) , ncol=10))
colnames(data1)=c("math" , "english" , "biology" , "music" , "R-coding", "data-viz" , "french" , "physic", "statistic", "sport" )

# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data1=rbind(rep(20,10) , rep(0,10) , data1)

# The default radar chart proposed by the library:
radarchart(data1)

# Custom the radarChart !
radarchart( data1  , axistype=1 ,

    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 ,

    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,

    #custom labels
    vlcex=0.8
    )
testd <- as.data.frame(colSums(data1))
names(testd) <- "total"
testd$skill <- rownames(testd)
rownames(testd[testd$total >=25,])
names(data1)
```
```{r}
for(i in unique(data$What.are.you.most.interested.in.)){
  print(data[data$What.are.you.most.interested.in.==i,])
}
```


```{r}
things = list(
  "name" = c("Harry Potter","Ron Weasley","Hermione Granger", "Draco Malfoy","Neville Longbottom"),
  "choice" = c("Ron Weasely","Harry Potter","Neville Longbottom","Harry James Potter","Hermione Granger"),
  "skill1" = sample(0:1,5,replace = T),
  "skill2" = sample(0:1,5,replace = T),
  "skill3" = sample(0:1,5,replace = T)
)
df = as.data.frame(things,stringsAsFactors = F)
rownames(df) <- seq(nrow(df))
print(df)

```
```{r}

```
```{r}
skips <- c()
for(i in seq(nrow(df))){
  if(df[i,]$choice != ""){
    if(df[i,]$choice %in% df$name){
      
      friend_pos = rownames(df[df$name == df[i,]$choice,])
      print(paste(df[i,]$name, " chose ",df[friend_pos,]$name))
      
      if(df[friend_pos,]$choice == df[i,]$name){
        print("and they chose each other")
        df[i,]$name <- paste(df[i,]$name,"@",df[friend_pos,]$name,sep="")
        print(df[i,]$name)
        skips <- c(skips,friend_pos)
        
      }
      else{
        print("but they didn't choose each other")
      }
    }
  }
}
df[!rownames(df) %in% skips,]
```


```{r}
for(i in seq(nrow(df))){
  if(df[i,]$choice != ""){
    if(df[i,]$choice %in% df$name){
      
      friend_pos = rownames(df[df$name == df[i,]$choice,])
      print(paste(df[i,]$name, " chose ",df[friend_pos,]$name))
      
      if(df[friend_pos,]$choice == df[i,]$name){
        
        print("...and they chose each other!")
      }
      else{
        print("...but they didn't choose each other")
      }
    }
    else{
      print(paste(df[i,]$name," didn't choose anyone in this class."))
    }
  }
}
```

```{r}
responses <- read.csv('data/fake2.csv',stringsAsFactors = F)
head(responses)
```

```{r}
names(responses)[4] <- "choice"
names(responses)[2] <- "name"
names(responses)
```
```{r}
check_for_partners <- function(df){
  for(i in seq(nrow(df))){
    if(df[i,]$choice != ""){
      if(df[i,]$choice %in% df$name){
        
        friend_pos = rownames(df[df$name == df[i,]$choice,])
        print(paste(df[i,]$name, " chose ",df[friend_pos,]$name))
        
        if(df[friend_pos,]$choice == df[i,]$name){
          
          print("...and they chose each other!")
        }
        else{
          print("...but they didn't choose each other")
        }
      }
      else{
        print(paste(df[i,]$name," didn't choose anyone in this class."))
      }
    }
  }
}

###

concat_partners <- function(df){
  skips <- c()
  for(i in seq(nrow(df))){
    if(df[i,]$choice != ""){
      if(df[i,]$choice %in% df$name){
        friend_pos = rownames(df[df$name == df[i,]$choice,])
        if(df[friend_pos,]$choice == df[i,]$name){
          df[i,]$name <- paste(df[i,]$name,"@",df[friend_pos,]$name,sep="")
          print(df[i,]$name)
          skips <- c(skips,friend_pos)
          
        }
      }
    }
  }
  df[!rownames(df) %in% skips,]
}

```


```{r}
partneredup <- concat_partners(responses)
```
```{r}
partneredup$assignment <- sample(1:10,93,replace = T)
```

```{r}
responses$assignment <- 0
for(i in seq(nrow(partneredup))){
  name <- partneredup$name[i]
  if(regexpr("@",name,fixed=T) > 0){
    partners <- strsplit(name,"@")
    responses[responses$name == partners[[1]][2],]$assignment <- partneredup$assignment[i]
    responses[responses$name == partners[[1]][1],]$assignment <- partneredup$assignment[i]
  }
  else{
    responses[responses$name == name,]$assignment <- partneredup$assignment[i]
  }
}
```

```{r}
responses[, c(2,ncol(responses))]
```


```{r}
partneredup[,c(2,ncol(partneredup))]
```
```{r}
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
  geom_point() +
  scale_x_log10()

gganimate(p)
```

